header (path, address) ::= <<
<html>
<head>
	<link rel="stylesheet" type="text/css" href="../static/style.css">
	<script type="text/javascript" src="../static/jquery.js"></script>
	<script type="text/javascript" src="../static/jquery.flot.js"></script>
	<script type="text/javascript" src="../static/jquery.flot.time.js"></script>
	<script type="text/javascript" src="../static/plot.js"></script>
</head>
<body>
<h1>
$path$
</h1>
<h2>
$address$
</h2>
<div>
	<p><a href="../index"> Main page </a></p>
	<p><a href="../queries">Queries</a></p>
	<p><a href="../fallback_contacts">Fallback contacts</a></p>
</div>
>>