package pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn; // Java Package generated by the BNF Converter.

public abstract class BasicExpr implements java.io.Serializable {
  public abstract <R,A> R accept(BasicExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.BasicExprAddC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.BasicExprSubC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.BasicExprMulC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.BasicExprDivC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.BasicExprModC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.BasicExprNegC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EBoolC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EIdentC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EFunC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EStrC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EIntC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EDblC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.ECondExprC p, A arg);
    public R visit(pl.edu.mimuw.cloudatlas.agent.interpreter.query.Absyn.EStmtC p, A arg);

  }

}
